{% set name = "ukkonen" %}
{% set version = "1.0.1" %}
{% set sha256 = "5f3fd0e9c1b2a7ea669382ec3928370f11882cec991c4d3757955b56d18895f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cffi                                # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
    - cffi
  run:
    - python
    - cffi

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/asottile/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Implementation of bounded Levenshtein distance (Ukkonen).
  description: Implementation of bounded Levenshtein distance (Ukkonen).
  doc_url: https://github.com/asottile/{{ name }}
  dev_url: https://github.com/asottile/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
    - deadsnakes-issues-bot
