{% set name = "ukkonen" %}
{% set version = "1.1.0" %}
{% set sha256 = "d238ac2751c967594a5ffd4d3e76a01ddcc63d01088a5c54e5fdd9e3cc7e1211" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/asottile/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-support-free-threaded.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
  host:
    - python
    - setuptools
    - pip
    - cffi
  run:
    - python
    - cffi

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/asottile/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Implementation of bounded Levenshtein distance (Ukkonen).
  description: Implementation of bounded Levenshtein distance (Ukkonen).
  doc_url: https://github.com/asottile/{{ name }}
  dev_url: https://github.com/asottile/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
    - deadsnakes-issues-bot
